# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auto_send_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(648, 480)
        MainWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.email_addr_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.email_addr_lineEdit.setObjectName("email_addr_lineEdit")
        self.gridLayout.addWidget(self.email_addr_lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.passwd_lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.passwd_lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwd_lineEdit_2.setObjectName("passwd_lineEdit_2")
        self.gridLayout.addWidget(self.passwd_lineEdit_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.host_lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.host_lineEdit_3.setObjectName("host_lineEdit_3")
        self.gridLayout.addWidget(self.host_lineEdit_3, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.file_path_lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.file_path_lineEdit_4.setText("")
        self.file_path_lineEdit_4.setCursorPosition(0)
        self.file_path_lineEdit_4.setObjectName("file_path_lineEdit_4")
        self.gridLayout.addWidget(self.file_path_lineEdit_4, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.ok_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.ok_pushButton.setObjectName("ok_pushButton")
        self.horizontalLayout.addWidget(self.ok_pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 6)
        self.verticalLayout.setStretch(1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "自动发送邮件"))
        self.groupBox.setTitle(_translate("MainWindow", "发送设置"))
        self.label.setText(_translate("MainWindow", "邮箱："))
        self.email_addr_lineEdit.setStatusTip(_translate("MainWindow", "发送方邮箱地址"))
        self.email_addr_lineEdit.setWhatsThis(_translate("MainWindow", "发送方邮箱地址"))
        self.label_2.setText(_translate("MainWindow", "密码："))
        self.passwd_lineEdit_2.setStatusTip(_translate("MainWindow", "发送方邮箱密码"))
        self.label_3.setText(_translate("MainWindow", "host："))
        self.label_4.setText(_translate("MainWindow", "附件文件夹："))
        self.file_path_lineEdit_4.setStatusTip(_translate("MainWindow", "附件所在文件夹"))
        self.ok_pushButton.setText(_translate("MainWindow", "确定"))
        self.pushButton_5.setText(_translate("MainWindow", "发送"))
